name: 'KanaChat'
version: '${project.version}'
main: net.ironingot.kanachat.KanaChat
api-version: '1.20'
authors: [ fubira, Shotadft ]
description: 'Alphabet to Hiragana convert + Kanji Translation'
website: 'https://github.com/shotadft/KanaChat-Spigot'
commands:
  kanachat:
    aliases:
      - japanize
      - kc
    usage: |
      /<command> [on|off] 
      /<command> kanji [on|off]
    description: 'Enable or Disable roma-ji japanese translation'
